compute_environment: LOCAL_MACHINE
debug: false
deepspeed_config:
  deepspeed_config_file: shell/debug/zero_stage1_config.json
  deepspeed_hostfile: shell/debug/hostfile-1
  deepspeed_multinode_launcher: pdsh
  zero3_init_flag: false
distributed_type: DEEPSPEED
downcast_bf16: 'no'
enable_cpu_affinity: false
machine_rank: 0
main_process_ip: 192.168.0.30
main_process_port: 52201
main_training_function: main
num_machines: 1
num_processes: 8
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
